name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      release_version: "vX.Y.Z"
      next_version: "vA.B.C"
    steps:
      - uses: actions/checkout@v2
      - name: Delete any existing tags / branches / PRs created by the test
        run:
          id = gh gh pr list --base release/vA.B.C | awk -v col=1 '{print $col}'
          [ $id ] && gh pr close $id
          git push origin :refs/heads/release/vA.B.C
          git push origin :refs/heads/pre-release/vA.B.C
      - name: Test the action
        uses: ./
        with:
          released_version: vX.Y.Z
          next_version: vA.B.C
      - name: Check for PR against the release branch
        run: |
          id = gh gh pr list --base release/vA.B.C | awk -v col=1 '{print $col}'
          [ $id ]

