name: Test

on: push

jobs:
  add-reviewer:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pulls/38/requested_reviewers \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{"team_reviewers":["@cucumber-actions/test"]}' \
            --fail
