name: Test

on: push

jobs:
  add-reviewer:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - run: |
          gh pr edit 38 --add-reviewer @cucumber-actions/test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
